/*
DEPLOYMENT INSTRUCTIONS:
1. Install Supabase CLI if not already:
   npm install -g supabase

2. Login to Supabase:
   supabase login

3. Link your project:
   supabase link --project-ref fnlvfdwphffgcpqufocs

4. Set the Resend API key secret:
   supabase secrets set RESEND_API_KEY=re_DPEmqyXR_5QK6jYiz8CAy4jppe43vSXyq
   Get your Resend API key from: https://resend.com
   Sign up free — 3,000 emails/month free tier
   Verify your domain or use their test domain

5. Deploy the function:
   supabase functions deploy send-daily-code-email

6. (Optional) Auto-Trigger on Database Inserts:
   If your database automatically generates the daily code row:
   - In Supabase Dashboard, go to: Database -> Webhooks -> Create Webhook.
   - Name: send_daily_code_email
   - Table: daily_codes
   - Event: INSERT (turn on only Insert)
   - Action: "Supabase Edge Function" -> select "send-daily-code-email"
   - Method: POST
   This will automatically trigger this email to admins whenever a new daily code is generated by the database!
*/

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 
    'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const payload = await req.json()
    const record = payload.record ?? payload
    const { code, valid_date } = record

    // Fetch admins to notify (daily code is for admin visibility/distribution)
    const { data: admins, error: admError } = await supabaseAdmin
      .from('profiles')
      .select('full_name, email')
      .in('role', ['admin', 'super_admin'])
      .eq('is_active', true)
      .not('email', 'is', null)

    if (admError) throw admError

    const allRecipients = admins ?? []

    // Format date nicely
    const dateObj = new Date(valid_date)
    const formattedDate = dateObj.toLocaleDateString(
      'en-IN', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      }
    )

    // Send email to each recipient using Resend
    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')
    
    const emailPromises = allRecipients.map(async (person) => {
      const response = await fetch(
        'https://api.resend.com/emails',
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${RESEND_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            from: 'Fuel Tracks <noreply@fueltracks.in>',
            to: person.email,
            subject: `Fuel Tracks — Today's Login Code (${formattedDate})`,
            html: `
              <div style="font-family: Arial, sans-serif; 
                          max-width: 480px; margin: 0 auto;
                          padding: 32px 24px;">
                
                <div style="text-align: center; margin-bottom: 24px;">
                  <h1 style="color: #1B3A6B; font-size: 24px; 
                             margin: 0;">FUEL TRACKS</h1>
                  <p style="color: #6B7280; font-size: 13px; 
                            margin: 4px 0 0;">
                    fuel monitoring now online..
                  </p>
                </div>

                <div style="background: #F0F7FF; 
                            border-radius: 12px; 
                            padding: 24px; 
                            text-align: center;
                            border: 1px solid #DBEAFE;">
                  <p style="color: #6B7280; font-size: 13px; 
                            margin: 0 0 8px;">
                    Today's Login Authentication Code
                  </p>
                  <p style="color: #1B3A6B; font-size: 13px;
                            margin: 0 0 16px;">
                    ${formattedDate}
                  </p>
                  <div style="background: #1B3A6B; 
                              border-radius: 12px;
                              padding: 16px 32px;
                              display: inline-block;">
                    <span style="color: white; 
                                 font-size: 48px; 
                                 font-weight: bold;
                                 letter-spacing: 16px;
                                 font-family: monospace;">
                      ${code}
                    </span>
                  </div>
                  <p style="color: #9CA3AF; font-size: 12px; 
                            margin: 16px 0 0;">
                    This code is valid for today only.
                    Do not share it with anyone outside 
                    the Fuel Tracks team.
                  </p>
                </div>

                <p style="color: #9CA3AF; font-size: 11px; 
                          text-align: center; margin-top: 24px;">
                  This is an automated message from 
                  Fuel Tracks Employee Portal.<br/>
                  Please do not reply to this email.
                </p>
              </div>
            `
          })
        }
      )
      return response.ok
    })

    await Promise.allSettled(emailPromises)

    return new Response(
      JSON.stringify({ 
        success: true, 
        recipients: allRecipients.length 
      }),
      { 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    )

  } catch (error) {
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { 
        status: 500,
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    )
  }
})
