import { useState, useEffect, useMemo, useCallback } from 'react'
import {
  Download, FileText, Users, Calendar, Filter, ChevronDown,
  AlertCircle, Loader2, Clock, CheckCircle, FileSpreadsheet,
} from 'lucide-react'
import toast from 'react-hot-toast'
import { format, parseISO, startOfMonth, endOfMonth, startOfWeek, endOfWeek, subMonths } from 'date-fns'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../lib/supabase'
import LoadingSpinner from '../../components/shared/LoadingSpinner'

/* ── helpers ─────────────────────────────────────────────────── */
const fmt = (d) => { try { return format(parseISO(d), 'd MMM yyyy') } catch { return d ?? '—' } }
const fmtTime = (d) => { try { return format(parseISO(d), 'h:mm a') } catch { return '—' } }
const fmtDt = (d) => { try { return format(parseISO(d), 'd MMM yyyy, h:mm a') } catch { return d ?? '—' } }
const iso = (d) => format(d, 'yyyy-MM-dd')

const today = () => iso(new Date())
const firstOfMonth = () => iso(startOfMonth(new Date()))

/* ── CSV builder ─────────────────────────────────────────────── */
function buildCSV(headers, rows) {
  const escape = (v) => {
    const s = String(v ?? '')
    return s.includes(',') || s.includes('"') || s.includes('\n')
      ? `"${s.replace(/"/g, '""')}"` : s
  }
  const lines = [headers.map(escape).join(',')]
  for (const row of rows) lines.push(row.map(escape).join(','))
  return lines.join('\r\n')
}

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

/* ── PDF helpers ─────────────────────────────────────────────── */
async function generatePDF({ title, period, adminName, adminId, headers, rows, filename }) {
  // dynamic import so main bundle stays lean
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header block
  doc.setFontSize(20)
  doc.setTextColor(0, 174, 239)
  doc.setFont('helvetica', 'bold')
  doc.text('FUEL TRACKS', 14, 18)

  doc.setFontSize(9)
  doc.setTextColor(107, 114, 128)
  doc.setFont('helvetica', 'normal')
  doc.text('Employee Attendance Portal', 14, 24)

  doc.setFontSize(13)
  doc.setTextColor(27, 58, 107)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, 33)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(107, 114, 128)
  if (period) doc.text(`Period: ${period}`, 14, 39)
  doc.text(`Generated on: ${format(new Date(), 'd MMM yyyy, h:mm a')}`, 14, period ? 44 : 39)

  // Divider
  doc.setDrawColor(219, 234, 254)
  doc.setLineWidth(0.5)
  doc.line(14, period ? 48 : 44, pageW - 14, period ? 48 : 44)

  // Table
  autoTable(doc, {
    startY: period ? 52 : 48,
    head: [headers],
    body: rows,
    styles: { fontSize: 7.5, cellPadding: 2.5, font: 'helvetica' },
    headStyles: {
      fillColor: [27, 58, 107],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [240, 247, 255] },
    didDrawPage: (data) => {
      const pageCount = doc.internal.getNumberOfPages()
      const currentPage = data.pageNumber
      doc.setFontSize(7)
      doc.setTextColor(107, 114, 128)
      const footerY = doc.internal.pageSize.getHeight() - 7
      doc.text('Fuel Tracks — Confidential', 14, footerY)
      doc.text(`Page ${currentPage} of ${pageCount}`, pageW / 2, footerY, { align: 'center' })
      doc.text(`Generated by: ${adminName} (${adminId})`, pageW - 14, footerY, { align: 'right' })
    },
  })

  doc.save(filename)
}

/* ── Action badge for recent exports table ───────────────────── */
const EXPORT_TYPE_LABEL = {
  attendance: 'Attendance Report',
  summary: 'Employee Summary',
}

export default function DataExport() {
  const { user: currentAdminUser, profile: currentAdminProfile } = useAuth()

  // Filter state
  const [exportType, setExportType]       = useState('attendance')   // 'attendance' | 'summary'
  const [fromDate, setFromDate]           = useState(firstOfMonth())
  const [toDate, setToDate]               = useState(today())
  const [employeeFilter, setEmployeeFilter] = useState('all')         // 'all' | 'specific'
  const [selectedEmployee, setSelectedEmployee] = useState(null)      // { id, full_name, employee_id }
  const [fileFormat, setFileFormat]       = useState('csv')           // 'csv' | 'pdf'

  // Employee list for dropdown
  const [empList, setEmpList]             = useState([])
  const [empSearch, setEmpSearch]         = useState('')
  const [empListLoading, setEmpListLoading] = useState(false)

  // Generate state
  const [generating, setGenerating]       = useState(false)

  // Recent exports
  const [recentExports, setRecentExports] = useState([])
  const [recentLoading, setRecentLoading] = useState(true)

  // Date range error
  const [dateError, setDateError]         = useState('')

  /* ── Load employees for dropdown ── */
  useEffect(() => {
    async function loadEmployees() {
      setEmpListLoading(true)
      const { data } = await supabase
        .from('profiles')
        .select('id, full_name, employee_id')
        .eq('role', 'employee')
        .eq('is_active', true)
        .order('employee_id', { ascending: true })
      setEmpList(data ?? [])
      setEmpListLoading(false)
    }
    loadEmployees()
  }, [])

  /* ── Load recent exports ── */
  const fetchRecentExports = useCallback(async () => {
    setRecentLoading(true)
    const { data } = await supabase
      .from('admin_audit_log')
      .select(`
        id, created_at, admin_employee_id, action_details,
        admin:profiles!admin_id(full_name)
      `)
      .eq('action_type', 'export_generated')
      .order('created_at', { ascending: false })
      .limit(10)
    setRecentExports(data ?? [])
    setRecentLoading(false)
  }, [])

  useEffect(() => { fetchRecentExports() }, [fetchRecentExports])

  /* ── Quick date select ── */
  function applyQuick(preset) {
    const now = new Date()
    if (preset === 'week')  { setFromDate(iso(startOfWeek(now, { weekStartsOn: 1 }))); setToDate(iso(endOfWeek(now, { weekStartsOn: 1 }))) }
    if (preset === 'month') { setFromDate(iso(startOfMonth(now))); setToDate(iso(endOfMonth(now))) }
    if (preset === 'last')  { const lm = subMonths(now, 1); setFromDate(iso(startOfMonth(lm))); setToDate(iso(endOfMonth(lm))) }
    if (preset === 'all')   { setFromDate('2020-01-01'); setToDate(iso(now)) }
    setDateError('')
  }

  /* ── Date validation ── */
  useEffect(() => {
    if (fromDate && toDate && fromDate > toDate) {
      setDateError('From date cannot be after To date.')
    } else {
      setDateError('')
    }
  }, [fromDate, toDate])

  /* ── Filtered employee list ── */
  const filteredEmpList = useMemo(() =>
    empList.filter(e =>
      e.full_name.toLowerCase().includes(empSearch.toLowerCase()) ||
      e.employee_id.toLowerCase().includes(empSearch.toLowerCase())
    ), [empList, empSearch])

  /* ── Preview text ── */
  const previewLines = [
    { label: 'Exporting', value: exportType === 'attendance' ? 'Attendance Report' : 'Employee Summary' },
    ...(exportType === 'attendance' ? [{ label: 'Period', value: `${fmt(fromDate + 'T00:00:00')} – ${fmt(toDate + 'T00:00:00')}` }] : []),
    { label: 'Employees', value: employeeFilter === 'all' ? 'All Employees' : (selectedEmployee ? `${selectedEmployee.full_name} (${selectedEmployee.employee_id})` : 'Select employee') },
    { label: 'Format', value: fileFormat.toUpperCase() },
  ]

  /* ── GENERATE REPORT ── */
  async function handleGenerate() {
    if (dateError) { toast.error(dateError); return }
    if (exportType === 'attendance' && (!fromDate || !toDate)) {
      toast.error('Please select a date range.'); return
    }
    if (employeeFilter === 'specific' && !selectedEmployee) {
      toast.error('Please select an employee.'); return
    }

    setGenerating(true)
    try {
      const dateSlug = format(new Date(), 'yyyy-MM-dd')

      if (exportType === 'attendance') {
        await generateAttendanceReport({ dateSlug })
      } else {
        await generateSummaryReport({ dateSlug })
      }

      supabase.from('admin_audit_log').insert({
        admin_id: currentAdminUser.id,
        admin_employee_id: currentAdminProfile?.employee_id,
        action_type: 'export_generated',
        action_details: {
          export_type: exportType,
          format: fileFormat,
          from_date: fromDate,
          to_date: toDate,
          employee_filter: employeeFilter === 'specific'
            ? selectedEmployee?.employee_id
            : 'all',
        },
      }).then(({ error }) => {
        if (error) console.error('[Audit Log] Failed to write:', error)
      })

      toast.success('Report downloaded successfully')
      await fetchRecentExports()
    } catch (err) {
      toast.error(err.message ?? 'Export failed. Please try again.')
    } finally {
      setGenerating(false)
    }
  }

  async function generateAttendanceReport({ dateSlug }) {
    // Fetch data
    let query = supabase
      .from('login_history')
      .select(`
        id, login_at, logout_at, hours_worked, session_duration_minutes, status, event_type,
        profile:profiles!profile_id(employee_id, full_name, is_active, role,
          details:employee_details!profile_id(department))
      `)
      .eq('status', 'success')
      .eq('event_type', 'login')
      .eq('profile.role', 'employee')
      .gte('login_at', `${fromDate}T00:00:00.000Z`)
      .lte('login_at', `${toDate}T23:59:59.999Z`)
      .order('login_at', { ascending: true })

    if (employeeFilter === 'specific' && selectedEmployee) {
      query = query.eq('profile_id', selectedEmployee.id)
    }

    const { data, error } = await query
    if (error) throw error

    const rows = (data ?? []).filter(r => r.profile?.role === 'employee')

    const headers = ['Employee ID', 'Employee Name', 'Department', 'Date', 'Login Time', 'Logout Time', 'Hours Worked', 'Session Duration (mins)']

    const tableRows = rows.map(r => {
      const profileDetails = (Array.isArray(r.profile?.details) ? r.profile.details[0] : r.profile?.details) || {}
      
      let logoutTimeLabel = 'Active Session'
      let hrsWorkedLabel = '—'
      let durationLabel = '—'

      if (r.logout_at) {
        logoutTimeLabel = fmtTime(r.logout_at)
        hrsWorkedLabel = r.hours_worked != null ? parseFloat(r.hours_worked).toFixed(2) : '—'
        durationLabel = r.session_duration_minutes ?? '—'
      } else {
        const loginTime = new Date(r.login_at).getTime()
        const nowTime = new Date().getTime()
        const diffMs = nowTime - loginTime
        const liveMins = Math.max(0, Math.round(diffMs / (1000 * 60)))
        const liveHrs = parseFloat((liveMins / 60).toFixed(2))

        logoutTimeLabel = 'Active Session (Online)'
        hrsWorkedLabel = `${liveHrs.toFixed(2)} (live)`
        durationLabel = `${liveMins} (live)`
      }

      return [
        r.profile?.employee_id ?? '—',
        r.profile?.full_name ?? '—',
        profileDetails.department ?? '—',
        fmt(r.login_at),
        fmtTime(r.login_at),
        logoutTimeLabel,
        hrsWorkedLabel,
        durationLabel,
      ]
    })

    const periodStr = `${fmt(fromDate + 'T00:00:00')} – ${fmt(toDate + 'T00:00:00')}`

    if (fileFormat === 'csv') {
      const csv = buildCSV(headers, tableRows)
      downloadBlob(csv, `fueltracks-attendance-${dateSlug}.csv`, 'text/csv;charset=utf-8;')
    } else {
      await generatePDF({
        title: 'Attendance Report',
        period: periodStr,
        adminName: currentAdminProfile?.full_name ?? 'Admin',
        adminId: currentAdminProfile?.employee_id ?? '—',
        headers,
        rows: tableRows,
        filename: `fueltracks-attendance-${dateSlug}.pdf`,
      })
    }
  }

  async function generateSummaryReport({ dateSlug }) {
    let query = supabase
      .from('profiles')
      .select(`
        id, employee_id, full_name, email, phone, role, is_active,
        details:employee_details!profile_id(department, designation, employment_type, date_of_joining, total_working_days, total_working_hours)
      `)
      .eq('role', 'employee')
      .eq('is_active', true)
      .order('employee_id', { ascending: true })

    if (employeeFilter === 'specific' && selectedEmployee) {
      query = query.eq('id', selectedEmployee.id)
    }

    const { data, error } = await query
    if (error) throw error

    // Fetch successful login history records to calculate analytics dynamically
    const { data: allHistory, error: histError } = await supabase
      .from('login_history')
      .select('profile_id, login_at, logout_at, hours_worked')
      .eq('status', 'success')

    if (histError) throw histError

    // Group successful logs by profile_id
    const historyMap = {}
    if (allHistory) {
      for (const item of allHistory) {
        const pid = item.profile_id
        if (!historyMap[pid]) {
          historyMap[pid] = { days: new Set(), hours: 0 }
        }
        if (item.login_at) {
          historyMap[pid].days.add(item.login_at.split('T')[0])
        }
        if (item.logout_at) {
          historyMap[pid].hours += parseFloat(item.hours_worked ?? 0)
        } else {
          // Running active session: live hours worked
          const loginTime = new Date(item.login_at).getTime()
          const nowTime = new Date().getTime()
          const diffMs = nowTime - loginTime
          const diffMins = Math.max(0, Math.round(diffMs / (1000 * 60)))
          const liveHrs = parseFloat((diffMins / 60).toFixed(2))
          historyMap[pid].hours += liveHrs
        }
      }
    }

    const headers = ['Employee ID', 'Full Name', 'Email', 'Phone', 'Department', 'Designation', 'Employment Type', 'Date of Joining', 'Total Working Days', 'Total Working Hours']

    const tableRows = (data ?? []).map(r => {
      const d = (Array.isArray(r.details) ? r.details[0] : r.details) || {}
      const stats = historyMap[r.id] || { days: new Set(), hours: 0 }
      return [
        r.employee_id ?? '—',
        r.full_name ?? '—',
        r.email ?? '—',
        r.phone ?? '—',
        d.department ?? '—',
        d.designation ?? '—',
        d.employment_type ?? '—',
        d.date_of_joining ? fmt(d.date_of_joining + 'T00:00:00') : '—',
        stats.days.size,
        stats.hours.toFixed(2),
      ]
    })

    if (fileFormat === 'csv') {
      const csv = buildCSV(headers, tableRows)
      downloadBlob(csv, `fueltracks-employee-summary-${dateSlug}.csv`, 'text/csv;charset=utf-8;')
    } else {
      await generatePDF({
        title: 'Employee Summary',
        period: null,
        adminName: currentAdminProfile?.full_name ?? 'Admin',
        adminId: currentAdminProfile?.employee_id ?? '—',
        headers,
        rows: tableRows,
        filename: `fueltracks-employee-summary-${dateSlug}.pdf`,
      })
    }
  }

  /* ── Segmented control helper ── */
  function SegBtn({ value, current, onChange, children }) {
    const active = value === current
    return (
      <button
        type="button"
        onClick={() => onChange(value)}
        style={{
          flex: 1, padding: '8px 0', fontSize: 13, fontWeight: 600, border: 'none',
          cursor: 'pointer', borderRadius: 6, fontFamily: 'Inter, sans-serif',
          background: active ? '#00AEEF' : 'transparent',
          color: active ? '#FFFFFF' : '#6B7280',
          transition: 'all 0.15s',
        }}
      >
        {children}
      </button>
    )
  }

  /* ── Quick date button ── */
  function QuickBtn({ label, preset }) {
    return (
      <button
        type="button"
        onClick={() => applyQuick(preset)}
        style={{
          padding: '5px 12px', fontSize: 12, fontWeight: 600,
          border: '1.5px solid #DBEAFE', borderRadius: 6,
          background: '#FFFFFF', color: '#00AEEF', cursor: 'pointer',
          fontFamily: 'Inter, sans-serif', transition: 'background 0.15s',
        }}
        onMouseEnter={e => { e.currentTarget.style.background = '#EFF6FF' }}
        onMouseLeave={e => { e.currentTarget.style.background = '#FFFFFF' }}
      >
        {label}
      </button>
    )
  }

  return (
    <div>
      {/* Page Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 24, fontWeight: 700, color: '#1B3A6B', margin: 0 }}>Export Data</h1>
        <p style={{ fontSize: 14, color: '#6B7280', margin: '4px 0 0' }}>Download attendance and employee reports</p>
      </div>

      {/* ── Configure Export Card ── */}
      <div style={{ background: '#FFFFFF', borderRadius: 12, boxShadow: '0 2px 12px rgba(0,174,239,0.08)', overflow: 'hidden', marginBottom: 20 }}>
        <div style={{ padding: '14px 20px', borderBottom: '1px solid #DBEAFE' }}>
          <h2 style={{ margin: 0, fontSize: 15, fontWeight: 700, color: '#1B3A6B', display: 'flex', alignItems: 'center', gap: 8 }}>
            <Filter size={15} color="#00AEEF" /> Configure Export
          </h2>
        </div>

        <div style={{ padding: 24 }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
            {/* LEFT: Filters */}
            <div>
              {/* Export Type */}
              <div style={{ marginBottom: 20 }}>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Export Type
                </label>
                <div style={{ display: 'flex', gap: 0, background: '#F0F7FF', borderRadius: 8, padding: 4 }}>
                  <SegBtn value="attendance" current={exportType} onChange={setExportType}>
                    📋 Attendance Report
                  </SegBtn>
                  <SegBtn value="summary" current={exportType} onChange={setExportType}>
                    👥 Employee Summary
                  </SegBtn>
                </div>
              </div>

              {/* Date Range (only for attendance) */}
              {exportType === 'attendance' && (
                <div style={{ marginBottom: 20 }}>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                    Date Range
                  </label>
                  <div style={{ display: 'flex', gap: 10, marginBottom: 10 }}>
                    <div style={{ flex: 1 }}>
                      <label htmlFor="from-date" style={{ display: 'block', fontSize: 11, color: '#9CA3AF', marginBottom: 4 }}>From</label>
                      <input
                        id="from-date"
                        type="date"
                        value={fromDate}
                        onChange={e => { setFromDate(e.target.value); setDateError('') }}
                        className="input-field"
                        style={{ fontSize: 13 }}
                        max={toDate}
                      />
                    </div>
                    <div style={{ flex: 1 }}>
                      <label htmlFor="to-date" style={{ display: 'block', fontSize: 11, color: '#9CA3AF', marginBottom: 4 }}>To</label>
                      <input
                        id="to-date"
                        type="date"
                        value={toDate}
                        onChange={e => { setToDate(e.target.value); setDateError('') }}
                        className="input-field"
                        style={{ fontSize: 13 }}
                        min={fromDate}
                      />
                    </div>
                  </div>
                  {dateError && (
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6, color: '#E8192C', fontSize: 12, marginBottom: 8 }}>
                      <AlertCircle size={13} /> {dateError}
                    </div>
                  )}
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    <QuickBtn label="This Week"  preset="week" />
                    <QuickBtn label="This Month" preset="month" />
                    <QuickBtn label="Last Month" preset="last" />
                    <QuickBtn label="All Time"   preset="all" />
                  </div>
                </div>
              )}

              {/* Employee Filter */}
              <div style={{ marginBottom: 20 }}>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  Employee Filter
                </label>
                <div style={{ display: 'flex', gap: 16, marginBottom: 10 }}>
                  {[['all', 'All Employees'], ['specific', 'Specific Employee']].map(([v, l]) => (
                    <label key={v} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#1B3A6B', cursor: 'pointer', fontWeight: 500 }}>
                      <input
                        type="radio"
                        name="employee-filter"
                        value={v}
                        checked={employeeFilter === v}
                        onChange={() => { setEmployeeFilter(v); setSelectedEmployee(null); setEmpSearch('') }}
                      />
                      {l}
                    </label>
                  ))}
                </div>
                {employeeFilter === 'specific' && (
                  <div>
                    <input
                      type="text"
                      placeholder="Search employee by name or ID…"
                      value={empSearch}
                      onChange={e => setEmpSearch(e.target.value)}
                      className="input-field"
                      style={{ fontSize: 13, marginBottom: 6 }}
                      id="emp-search-filter"
                    />
                    {empListLoading ? (
                      <div style={{ padding: 12, textAlign: 'center' }}>
                        <LoadingSpinner size="sm" />
                      </div>
                    ) : (
                      <div style={{
                        maxHeight: 160, overflowY: 'auto',
                        border: '1.5px solid #DBEAFE', borderRadius: 8,
                        background: '#FFFFFF',
                      }}>
                        {filteredEmpList.length === 0 ? (
                          <div style={{ padding: 12, textAlign: 'center', color: '#9CA3AF', fontSize: 12 }}>
                            No employees found
                          </div>
                        ) : filteredEmpList.map(emp => (
                          <div
                            key={emp.id}
                            onClick={() => { setSelectedEmployee(emp); setEmpSearch(emp.full_name) }}
                            style={{
                              padding: '9px 14px', cursor: 'pointer',
                              fontSize: 13, color: '#1B3A6B',
                              background: selectedEmployee?.id === emp.id ? '#EFF6FF' : 'transparent',
                              fontWeight: selectedEmployee?.id === emp.id ? 600 : 400,
                              display: 'flex', justifyContent: 'space-between',
                              borderBottom: '1px solid #F0F7FF',
                            }}
                            onMouseEnter={e => { if (selectedEmployee?.id !== emp.id) e.currentTarget.style.background = '#F8FBFF' }}
                            onMouseLeave={e => { if (selectedEmployee?.id !== emp.id) e.currentTarget.style.background = 'transparent' }}
                          >
                            <span>{emp.full_name}</span>
                            <span style={{ color: '#6B7280', fontSize: 11 }}>{emp.employee_id}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* File Format */}
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#6B7280', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                  File Format
                </label>
                <div style={{ display: 'flex', gap: 0, background: '#F0F7FF', borderRadius: 8, padding: 4, maxWidth: 200 }}>
                  <SegBtn value="csv" current={fileFormat} onChange={setFileFormat}>CSV</SegBtn>
                  <SegBtn value="pdf" current={fileFormat} onChange={setFileFormat}>PDF</SegBtn>
                </div>
              </div>
            </div>

            {/* RIGHT: Preview + Export button */}
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              {/* Preview Summary */}
              <div style={{
                background: '#F8FBFF', border: '1.5px solid #DBEAFE', borderRadius: 12,
                padding: 20, marginBottom: 20, flex: 1,
              }}>
                <h3 style={{ margin: '0 0 16px', fontSize: 13, fontWeight: 700, color: '#1B3A6B', display: 'flex', alignItems: 'center', gap: 8 }}>
                  <FileText size={14} color="#00AEEF" /> Export Preview
                </h3>
                {previewLines.map(({ label, value }) => (
                  <div key={label} style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: 10, marginBottom: 10, borderBottom: '1px solid #DBEAFE' }}>
                    <span style={{ fontSize: 12, color: '#6B7280', fontWeight: 500 }}>{label}</span>
                    <span style={{ fontSize: 12, color: '#1B3A6B', fontWeight: 700, maxWidth: '60%', textAlign: 'right' }}>{value}</span>
                  </div>
                ))}
              </div>

              {/* Generate button */}
              <button
                type="button"
                onClick={handleGenerate}
                disabled={generating || !!dateError}
                className="btn-primary"
                style={{ width: '100%', padding: '13px 0', fontSize: 14, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 }}
                id="generate-export-btn"
              >
                {generating ? (
                  <>
                    <Loader2 size={16} style={{ animation: 'spin 0.7s linear infinite' }} />
                    Generating…
                  </>
                ) : (
                  <>
                    <Download size={16} />
                    Generate &amp; Download Report
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* ── Recent Exports Card ── */}
      <div style={{ background: '#FFFFFF', borderRadius: 12, boxShadow: '0 2px 12px rgba(0,174,239,0.08)', overflow: 'hidden' }}>
        <div style={{ padding: '14px 20px', borderBottom: '1px solid #DBEAFE' }}>
          <h2 style={{ margin: 0, fontSize: 15, fontWeight: 700, color: '#1B3A6B', display: 'flex', alignItems: 'center', gap: 8 }}>
            <Clock size={15} color="#00AEEF" /> Recent Exports
          </h2>
        </div>

        {recentLoading ? (
          <div style={{ display: 'flex', justifyContent: 'center', padding: 40 }}>
            <LoadingSpinner size="md" />
          </div>
        ) : recentExports.length === 0 ? (
          <div style={{ padding: 48, textAlign: 'center' }}>
            <FileSpreadsheet size={36} color="#DBEAFE" style={{ marginBottom: 12 }} />
            <p style={{ margin: 0, fontSize: 14, color: '#6B7280' }}>No exports yet</p>
            <p style={{ margin: '4px 0 0', fontSize: 12, color: '#9CA3AF' }}>Your export history will appear here</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#F8FBFF' }}>
                  {['Date & Time', 'Exported By', 'Type', 'Period', 'Format'].map(h => (
                    <th key={h} style={{
                      padding: '10px 16px', textAlign: 'left',
                      fontSize: 12, fontWeight: 600, color: '#6B7280',
                      borderBottom: '1px solid #DBEAFE', whiteSpace: 'nowrap',
                    }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {recentExports.map((row, i) => {
                  const d = row.action_details ?? {}
                  return (
                    <tr
                      key={row.id ?? i}
                      style={{ borderBottom: '1px solid #F0F7FF' }}
                      onMouseEnter={e => e.currentTarget.style.background = '#F8FBFF'}
                      onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                    >
                      <td style={{ padding: '12px 16px', fontSize: 12, color: '#6B7280', whiteSpace: 'nowrap' }}>
                        {fmtDt(row.created_at)}
                      </td>
                      <td style={{ padding: '12px 16px' }}>
                        <p style={{ margin: 0, fontSize: 13, fontWeight: 600, color: '#1B3A6B' }}>
                          {row.admin?.full_name ?? 'Admin'}
                        </p>
                        <p style={{ margin: 0, fontSize: 11, color: '#9CA3AF' }}>{row.admin_employee_id}</p>
                      </td>
                      <td style={{ padding: '12px 16px' }}>
                        <span style={{
                          display: 'inline-block', padding: '2px 10px', borderRadius: 9999,
                          fontSize: 11, fontWeight: 600,
                          background: d.export_type === 'attendance' ? 'rgba(0,174,239,0.1)' : 'rgba(139,92,246,0.1)',
                          color: d.export_type === 'attendance' ? '#00AEEF' : '#7C3AED',
                        }}>
                          {EXPORT_TYPE_LABEL[d.export_type] ?? d.export_type ?? '—'}
                        </span>
                      </td>
                      <td style={{ padding: '12px 16px', fontSize: 12, color: '#6B7280', whiteSpace: 'nowrap' }}>
                        {d.from_date && d.to_date
                          ? `${fmt(d.from_date + 'T00:00:00')} – ${fmt(d.to_date + 'T00:00:00')}`
                          : '—'}
                      </td>
                      <td style={{ padding: '12px 16px' }}>
                        <span style={{
                          display: 'inline-block', padding: '2px 10px', borderRadius: 9999,
                          fontSize: 11, fontWeight: 700,
                          background: d.format === 'pdf' ? 'rgba(232,25,44,0.08)' : 'rgba(22,163,74,0.08)',
                          color: d.format === 'pdf' ? '#E8192C' : '#16A34A',
                          textTransform: 'uppercase',
                        }}>
                          {d.format ?? '—'}
                        </span>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Responsive grid stacking */}
      <style>{`
        @media (max-width: 800px) {
          .export-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  )
}
